### ISSUE TITLE
Create Student Sections

### ISSUE THREAD

**Issue by ambersu123** [chingu-voyages/v29-toucans-team-01#12]
**__Feature Description__**
Create the Student Section so that the students can search the tutors

**__Major User Stories/tasks__**
- [ ]  Search for tutors
- [ ] User Story or Task #2
- [ ] Additional User Stories or Tasks as necessary

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
