### ISSUE TITLE
Tutors are listing their profiles so that the students can find them

### ISSUE THREAD

**Issue by ambersu123** [chingu-voyages/v29-toucans-team-01#17]
**__Feature Description__**
Tutors are listing their profiles so that the students can find them

**__Major User Stories/tasks__**
- [ ]  User Story- Tutors sharing contact info, resources, bookmarks
- [ ] Task -  Set up Git Repository, initialize the repository, Git workflow or structure
- [ ] Additional User Stories or Tasks as necessary

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
